### ISSUE TITLE
Resource files not there after pip install

### ISSUE THREAD

**Issue by yoavram** [yoavram/curveball#148]
- `data` folder empty
- `plate_templates` folder empty
The folders contain `__init__.py` but not CSV or XLSX files.

**Comment by manelavanya** [comment]
@yoavram Finding the same problem, except there isn't even a `data` folder in the `curveball` folder. Installed on macOS Sierra. Looking forward to using Curveball!

**Comment by yoavram** [comment]
The data file can be found here: https://github.com/yoavram/curveball/raw/master/data/Tecan_280715.xlsx
The plate file can be found here: https://github.com/yoavram/curveball/raw/master/plate_templates/G-RG-R.csv

**Comment by yoavram** [comment]
I added links to the files from the tutorial.
