### ISSUE TITLE
as_matrix depreciated in pandas

### ISSUE THREAD

**Issue by chofski** [yoavram/curveball#154]
Having attempted to run the fit_model function on data from the BioTekSynergy.xlsx example file I get an error that "as_matrix does not exist". This turns out to be due to the function being depreciated. This should instead be replaced with "to_numpy". In my patched version this now runs successfully.

**Comment by yoavram** [comment]
Would you be willing to open a pull request with your patch? 
Also are your sure it’s .to_numpy and not .values?

**Comment by chofski** [comment]
Either works. I'll push my patched version, but you might want to run some more thorough test to be sure this doesn't impact other parts of the codebase.
